### ISSUE TITLE
Limit Size Upload

### ISSUE THREAD

**Issue by mpetyx** [bradleyg/django-s3direct#62]
Hello,
I would like to ask if there is an option to limit the size upload somehow through the settings for example on my declaration below,
`'imgs': ('uploads/imgs', lambda u: True, ['image/jpeg', 'image/png'],),`

if it could be,
`'imgs': ('uploads/imgs', lambda u: True, ['image/jpeg', 'image/png'],'10MB'),`
or
`'imgs': ('uploads/imgs', lambda u: True, ['image/jpeg', 'image/png'], lambda file: file._size> 10*1024*1024),`

Is there a default field or parameter to monitor in order to throw an exception if someone goes above my preferred threshold?
I am looking for something similar to the discussions [here](http://stackoverflow.com/questions/6195478/max-image-size-on-file-upload) and [here](http://stackoverflow.com/questions/2472422/django-file-upload-size-limit).
Thank you very much in advance!

**Comment by ivanvenosdel** [comment]
I would like to see this feature as well and have put some thought into it's implementation. 

Since django-s3direct never touches the file directly (by design). It would need to rely on S3 to do the content-size checking. That is achieved by way of a "content-length-range" in the [post policy](http://docs.aws.amazon.com/AmazonS3/latest/API/sigv4-HTTPPOSTConstructPolicy.html).

Presently the policy is [constructed](https://github.com/bradleyg/django-s3direct/blob/master/s3direct/utils.py#L41) using the positional values provided in the value of each key within the S3DIRECT_DESTINATIONS setting. 

For these advanced cases, instead of adding a positional that is specific to this condition add one that is for a dictionary of arbitrary conditions to add to the post policy. I think that change would better shield the project maintainers from having to field future issues for new one-off-site-specific conditions yet still make it possible for those that would like to use them differently.

I might be able to do a PR for this later if the project maintainer expresses interest.

**Comment by bradleyg** [comment]
Definitely interested :)

**Comment by ivanvenosdel** [comment]
Great! I should have something in ~1-2wks.
