### ISSUE TITLE
Question: Integration with django-rest-framework

### ISSUE THREAD

**Issue by vasilycrespo** [bradleyg/django-s3direct#92]
Hello,

 I've just installed the plugin and seems to be working great from the administrator, however I would like to know if there is a way to make it work too from django-rest-framework, it seem to be accepting a string field where S3DirectField is defined on the model, I have tried also to pass it a base64 image with no success.

Best regards!

**Comment by bradleyg** [comment]
Unfortunately this library doesn't work like that. It uploads files directly to S3, rather than to an endpoint on your server. So sending anything to that particular field via drf will do nothing.

The only thing you could do is make 2 separate calls from your frontend, or accept the file on your server and push it to S3 server side, perhaps using a library like [Django Storages](http://django-storages.readthedocs.io/en/latest/backends/amazon-S3.html).
